# Generated by Django 3.1.2 on 2021-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='for_fone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='for_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
