# Generated by Django 3.1.2 on 2021-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiodepagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meiodepagamento',
            name='mei_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
