# Generated by Django 3.2.8 on 2021-10-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20210826_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['for_fornecedor'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
