# Generated by Django 3.2.8 on 2023-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
