# Generated by Django 3.1.2 on 2021-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat_despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natdespesa',
            name='nat_natdespesa',
            field=models.CharField(max_length=100, verbose_name='Natureza da Despesa'),
        ),
    ]
