# Generated by Django 3.1.2 on 2021-08-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('nat_despesas', '0001_initial'),
        ('meiodepagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_datadespesa', models.DateField(verbose_name='Data Despesa')),
                ('des_valordespesa', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('des_status', models.CharField(choices=[('1', 'PAGO'), ('2', 'A PAGAR'), ('3', 'VENCIDO')], max_length=1, verbose_name='Status')),
                ('des_itensdespesa', models.TextField(blank=True, max_length=255, null=True, verbose_name='Itens da despesa')),
                ('des_obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('meiodepagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meiodepagamentos.meiodepagamento', verbose_name='Meio de Pagamento')),
                ('nat_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nat_despesas.natdespesa', verbose_name='Natureza da Despesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'db_table': 'despesa',
                'ordering': ['nat_despesa'],
            },
        ),
    ]
