# Generated by Django 3.1.2 on 2021-07-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meiodepagamentos', '0001_initial'),
        ('despesas', '0002_auto_20210711_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='meiodepagamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meiodepagamentos.meiodepagamento', verbose_name='Meio de Pagamento'),
            preserve_default=False,
        ),
    ]
