# Generated by Django 3.1.2 on 2021-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_auto_20210822_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='des_datadespesa',
            field=models.DateField(blank=True, null=True, verbose_name='Data Despesa'),
        ),
    ]
