# Generated by Django 3.1.2 on 2021-08-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_auto_20210822_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-des_datadespesa', 'nat_despesa'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
    ]
