# Generated by Django 3.1.2 on 2021-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_auto_20210711_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='des_itensdespesa',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Itens da despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='des_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
