# Generated by Django 3.1.2 on 2021-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0006_auto_20210711_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='des_status',
            field=models.CharField(choices=[('1', 'PAGO'), ('2', 'A PAGAR'), ('3', 'VENCIDO')], default='1', max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
