# Generated by Django 3.1.2 on 2021-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesa_meiodepagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='des_itensdespesa',
            field=models.TextField(max_length=255, verbose_name='Itens da despesa'),
        ),
    ]
