# Generated by Django 3.1.2 on 2021-07-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_auto_20210711_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['nat_despesa'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='des_modalidadecartao',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='des_natdespesa',
        ),
    ]
